#!/usr/bin/env python3
# @load-order 30
"""Generate orb drop rows for all creatures based on rank.

Queries creature_template for all creatures with a loot table that award XP,
then generates INSERT INTO creature_loot_template rows referencing the
rank-appropriate orb loot pool at 30% chance.

Rank mapping:
  0 (Normal)     -> LOOT_FORGE_POOL_COMMON
  1 (Elite)      -> LOOT_FORGE_POOL_UNCOMMON
  2,3,4 (Rare Elite, World Boss, Rare) -> LOOT_FORGE_POOL_RARE

When a lootid is shared by creatures of different ranks, the highest rank
determines which pool is used.

Output: content/orb_creature_drops.sql (regenerated on build)
"""

import argparse
import sys
from pathlib import Path

import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
MOD_DIR = SCRIPT_DIR.parent
OUTPUT_PATH = MOD_DIR / 'content' / 'orb_creature_drops.sql'

RANK_TO_POOL = {
    0: 'LOOT_FORGE_POOL_COMMON',
    1: 'LOOT_FORGE_POOL_UNCOMMON',
}
# Ranks 2, 3, 4 all map to rare
RARE_POOL = 'LOOT_FORGE_POOL_RARE'

CHANCE = 30


def query_loot_ranks(db_config):
    """Query distinct lootids and their max rank from creature_template."""
    import mysql.connector

    conn = mysql.connector.connect(
        host=db_config['host'], port=db_config['port'],
        user=db_config['user'], password=db_config['password'],
        database=db_config['world_db']
    )
    cursor = conn.cursor()

    cursor.execute("""
        SELECT lootid, MAX(`rank`) AS max_rank
        FROM creature_template
        WHERE lootid > 0 AND (flags_extra & 64) = 0
        GROUP BY lootid
    """)
    rows = cursor.fetchall()
    conn.close()
    return rows


def generate_sql(loot_ranks):
    """Generate INSERT...VALUES SQL with symbolic token references."""
    # Group lootids by pool
    pool_groups = {}
    for lootid, max_rank in loot_ranks:
        pool = RANK_TO_POOL.get(max_rank, RARE_POOL)
        pool_groups.setdefault(pool, []).append(lootid)

    lines = []
    lines.append("-- Generated by prebuild/generate_creature_drops.py -- DO NOT EDIT")
    lines.append("-- Orb drops for all creatures based on rank.")
    lines.append("-- %d total loot tables across %d pools." % (
        sum(len(v) for v in pool_groups.values()), len(pool_groups)))
    lines.append("")

    pool_order = [
        ('LOOT_FORGE_POOL_COMMON', 'Normal (rank 0)'),
        ('LOOT_FORGE_POOL_UNCOMMON', 'Elite (rank 1)'),
        ('LOOT_FORGE_POOL_RARE', 'Rare Elite / World Boss / Rare (rank 2-4)'),
    ]

    for pool_token, description in pool_order:
        lootids = pool_groups.get(pool_token)
        if not lootids:
            continue

        lootids.sort()
        lines.append("-- %s: %s (%d loot tables)" % (pool_token, description, len(lootids)))
        lines.append("INSERT INTO creature_loot_template")
        lines.append("    (Entry, Item, Reference, Chance, QuestRequired, LootMode, GroupId, MinCount, MaxCount, Comment)")
        lines.append("VALUES")

        value_lines = []
        for lootid in lootids:
            value_lines.append(
                "    (%d, %s, %s, %d, 0, 1, 0, 1, 1, 'Forge Orb')"
                % (lootid, pool_token, pool_token, CHANCE)
            )

        lines.append(",\n".join(value_lines) + ";")
        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description='Generate creature orb drop SQL')
    parser.add_argument('--config', required=True, help='Path to project.yaml')
    parser.add_argument('--id-assignments', required=False, help='(unused)')
    args = parser.parse_args()

    print("[PoeOrbs] Generating creature orb drop SQL...")

    with open(args.config) as f:
        config = yaml.safe_load(f)

    db_config = config.get('database')
    if not db_config:
        print("  ERROR: No 'database' section in project.yaml")
        sys.exit(1)

    print("  Querying creature_template for loot tables...")
    loot_ranks = query_loot_ranks(db_config)
    print("  Found %d distinct loot tables" % len(loot_ranks))

    sql = generate_sql(loot_ranks)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, 'w', newline='\n') as f:
        f.write(sql)

    print("  Wrote %s" % OUTPUT_PATH)
    print("[PoeOrbs] Creature drops done.")


if __name__ == '__main__':
    main()